services:
  - type: web
    name: my-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html